### PR TITLE
Added additional packages to allow the image to be built successfully

### PR DESCRIPTION
**Pull request by tachoknight**
The Dockerfile did not build successfully due to some packages being renamed, etc. I made some changes to get the image built successfully and have been able to run the Concerto container for testing without any issues.

### CODE REVIEW

**Comment by mfrederickson** [comment]
@tachoknight thanks for your work on this.  I am not very familiar with docker, so please bear with me amd correct me if I am doing something wrong...   I pulled down your master branch and ran `docker build -t concerto .` and got the following error:
image

I am running Ubuntu 16.04.3 LTS with Docker version 1.12.6, build 78d1802.

**Comment by tachoknight** [comment]
Hi Marvin-

Hmm, I did a fresh pull and it built okay. Maybe try removing any 
intermediate containers (or any images labeled concerto) and try again. 
What version of Docker are you using?

Ron

**Comment by mfrederickson** [comment]
> I am running Ubuntu 16.04.3 LTS with Docker version 1.12.6, build
> 78d1802.

I have no other containers.

**Comment by tachoknight** [comment]
Oh, I think I know the issue; you probably already have a log 
sub-directory in the concerto directory (same directory as the 
Dockerfile). Delete the log directory and it should work.

There's a trick to getting around this where if you do 'mkdir -p <dir>' 
it will succeed regardless of whether the directory exists or not (and 
preserve the contents, if any); you can add the -p to the Dockerfile, 
but personally I'd just delete the log directory as you want it to be 
empty in the container.

Ron

**Comment by mfrederickson** [comment]
I added the -p and got farther, but still having trouble...
image

**Comment by tachoknight** [comment]
Hm, weird. Say, can you try setting your current concerto directory aside and do a new clone of the repo and try again?

**Comment by mfrederickson** [comment]
It worked.

**Pull request merged**
