### PR TITLE
update for devise 3.4

### PR DESCRIPTION
**Pull request by mfrederickson**
bundle updated and slightly modified for devise 3.4. also changed the travis.yml and our db initializer so travis runs like we would (with our app running the migrations) and locally rake test works also (without running twice or having to manually create the db first).

-- previously --
Since I don't know how to get travis to check this commit/branch, I'm going to create this PR, but please don't merge it until I change this message.

### CODE REVIEW

**Comment by zr2d2** [comment]
Long-term, you would add the branch name [here](https://github.com/concerto/concerto/blob/master/.travis.yml#L22) to get it to build on new commits. A PR is the way I would go for testing like this. And **some people** shouldn't be so trigger-happy

**Comment by augustf** [comment]
This is how we do Science. Also, it's good to be a king.

**Comment by mfrederickson** [comment]
@zr2d2 @augustf I'm going to change the devise restriction from ~>3.0.0 to just ~>3 and run a `bundle update` and then add the Gemfile and Gemfile.lock here so it actually comes up to devise 3.4, ok?

**Comment by augustf** [comment]
Sure! If we can do it without issues, I'd like to do a comprehensive bundle update.

**Comment by mfrederickson** [comment]
There were no problems when I did it locally, your majesty.

**Comment by augustf** [comment]
Haha indeed good esquire! I got burned by #1157 last I tried it.

**Comment by zr2d2** [comment]
You could technically use~> 3.0, but sure. @augustf, that would only work
if it's a dependency problem, but i thought the problem was with the tables
not being created

**Comment by mfrederickson** [comment]
If the screens work and the player works with the new devise then I'm fine with going ahead.  I'm away from the computer for the next couple hours.

**Comment by mfrederickson** [comment]
The latest concerto player image seems to work fine with this branch (with tokens).

**Pull request merged**
