### PR TITLE
use __FILE__ for logging

### PR DESCRIPTION
**Pull request by mfrederickson**
Added the logging to those where it was missing, and also swapped devise and secret token initializers since the newer devise will need the token.

### CODE REVIEW

**Comment by augustf** [comment]
@mfrederickson So you're thinking the order change will overcome the issue we were discussing in the Devise upgrade ticket?

**Comment by mfrederickson** [comment]
No.  That's something else.  Devise 3.latest needs a secret key token, we're currently on 3.0.4 I think.  I'm going to look into that other problem later today-- it could be that it wont be a problem with the latest devise (or maybe easier to find a solution for).

**Comment by zr2d2** [comment]
I like the interpolation of  `File.basename`. Now that all the messages are the same, could the initializer be passed as a block to a logging method to dry this up?

**Comment by mfrederickson** [comment]
I'm not sure Zach, I looked for a before/after that would fire for each initializer, but it looks like only one fires before all of the them and only one after.

**Comment by augustf** [comment]
@mfrederickson I think we can, in the new Devise config, just use our existing secret token for devise by setting it in the devise initializer, assuming it's in scope at that point.

**Comment by mfrederickson** [comment]
@augustf it will be since we just swapped their order.

**Comment by zr2d2** [comment]
just because it comes before doesn't mean it will be in scope. Ruby has
[scope gates](http://hopsoft.github.io/blog/ruby-metaprogramming-idioms/),
so scoping behaves differently than in other languages


Zach Rowe

**Comment by augustf** [comment]
Luckily, I don't think anything that esoteric will come into play. The token is/can be stored in the DB or an environment variable.

**Comment by zr2d2** [comment]
I would argue that knowing how ruby works is important when writing in
ruby, it is for your edification


Zach Rowe

**Comment by augustf** [comment]
"Questions are a burden to others; answers a prison for oneself." --The Prisoner

**Comment by mfrederickson** [comment]
Thanks for the edification and the banter-- both were enjoyable.

**Pull request merged**
