### PR TITLE
Strict Priority shuffle

### PR DESCRIPTION
**Pull request by garci66**
Add support for a "strict priority" shuffle that only displays feeds of the same "priority" (frequency) in descending order. If there is content tagged as "show very freqently" (weight 5), then only feeds with weight 5 would be shown. Only when no weight 5 feeds (with content) exist, then feeds of weight 4 would be shown and so on. 

This allows a feed to be able to preempt other feeds in fields as needed.

Probably does not satisfy the "emergency broadcast system" that was discussed in the roadmap in the Wiki but could be of use for hotels, etc where at certain times only specific content should be shown (like, if concerto screen is used to show the event in a meeting room), but otherwise, promos or ads could be shown.

### CODE REVIEW

**Comment by mfrederickson** [comment]
@garci66 would the content scheduling plugin work better for specifying when content should appear for cases such as events in a meeting room, etc?

**Comment by mfrederickson** [comment]
@garci66 can you add some tests for this?

**Comment by garci66** [comment]
I can definitively add test cases, but I have not yet done anything like it so far. I 'll take a look at some of the test-cases to see how to add some test-cases.

I only now see the content-schedulin-plugin.. which has no readme whatsoever so not sure exactly what it's supposed to do. Maybe indeed, it solves the issues I have. I'll take a look ASAP. you can keep the PR open in the meantime.

Thanks!

PS.  I am also looking into some hybrid content plugin (where we load an image AND text into an html style content). Is it something like this available? I noticed the "mixed content" plugin helps to schedule images and text to the same field, but not simultaneously...

**Comment by mfrederickson** [comment]
I don't know of any hybrid content types plugins.

**Comment by garci66** [comment]
Thanks! I'm working on the test-cases now. I just installed the content-scheduling plugin and from what I see, it allows you to set recurring schedules, for content, but the content will still be shuffled with other feeds scheduled for the same field. For the particular use-case I needed, there is no fixed schedule, but only feeds that should display only content from this feed as long as its active, and otherwise fall back to "regular programming" of the rest of the feeds.

**Comment by garci66** [comment]
Hi,

Im sorry but to be perfectly honest, Ruby / Rails is really not my area of expertise and haven't figured out how to properly write a test-case for it. I couldn't find any test-cases for the other shufflers (which I could have used as a starting point) so I don't think I can add a test case for it.

I know this is far from ideal and would make the contribution not acceptable, or at least, a lot less desirable, but is there any chance someone can point me towards a simple sample or anything like it?

I've been using a branch with this scheduler in production for over two months, so far with no issues. I know this is not a test-case, but just wanted to provide the data point.

**Comment by mfrederickson** [comment]
@garci66 ah yes... my apologies... let me work on some test cases...

**Comment by mfrederickson** [comment]
@garci66 I've made some changes, but they're on a more up to date branch.  I'd like to create a pull request to merge them into your branch here, but I think you need to bring yours up to date first.  I think you can do that by the following, where the upstream remote points to the concerto/concerto repo and the origin remote points to garci66/concerto.
```
git remote add upstream https://github.com/concerto/concerto.git  # add a new remote called 'upstream' that points to concerto's repo
git checkout master  # go to your local master branch
git fetch upstream  # pull down the latest changes from the concerto repo
git merge upstream/master # merge concerto's master branch into yours to bring it up to date
git push origin master # update your repo on github
git checkout priority-shuffle  # go to your local priority-shuffle branch
git merge master # merge the latest updates into your local branch to bring it up to date
git push origin priority-shuffle # update your repo on github
```
Then I can create a PR into your branch (and it shouldn't include all the other unrelated changes).  If you're going to do the above, I'd cut and paste it line by line one at a time.

Or I can just create a new PR against concerto/master and we can close this one.

**Comment by garci66** [comment]
Hi!
Sorry, we were on a long weekend here in Argentina. Back online now. I have my repo with the priority-shuffle branch ready. You can do a PR against it or I can create a new one. But we can close this one. Thanks again for everything!!

**Comment by mfrederickson** [comment]
closed in deference to #1388 which includes all these changes and the test cases

**Pull request closed without merging**
